module.exports = {
  MESSAGES: {
    USERS: {
      USER_ID_REQUIRED: "User Id is required.",
      USER_LOGIN_SUCCESS: "User login successfully.",
      USER_LOGIN_FAILED: "User login failed.",
      NOT_FOUND: "Sorry we could not find this user.",
      EMAIL_ALREADY_EXISTS: "A user with this email address already exists.",
      EMAIL_ALREADY_VERIFIED: "This email has already verified.",
      EMAIL_RESENT: "Email resent successfully.",
      USER_VERIFIED_SUCCESSFULLY: "User verified successfully.",
      FORGOT_PASSWORD_SENT_SUCCESS: "Forgot password email send successfully.",
      PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully.",
      USER_ADDED: "User added successfully.",
      USER_UPDATED: "User updated successfully.",
      USER_UPDATED_FAILED: "User update Failed.",
      USER_LIST_FAILED: "User list Failed.",
      FAILED_TO_CREATE_USER: "Failed to create user.",
      USER_TYPES_LISTED: "Users Types are listed!",
      USER_LISTED: "Users are listed!",
    },
    ORGANIZATION: {
      INVALID_STEP_KEY: "Invalid step key.",
      ORGANIZATION_UPDATED: "Organization updated successfully.",
      FAILED_TO_UPDATED_ORGANIZATION: "Failed to update organization.",
    },
    AUTH: {
      INCORRECT_PASSWORD: "Password is incorrect.",
      CORRECT_OTP: "Otp is verified.",
      INCORRECT_OTP: "OTP not generated yet or already verified!",
      OTP_ALREADY_VERIFIED: "OTP not generated yet or already verified!",
      VERIFY_OTP_FAILED: "Otp verification failed.",
      NO_PERMISSION_AVAILABLE: "No permissions available.",
    },
    SIGNUP: {
      SIGNUP_COMPLETED: "signup successfully.",
      FAILED_TO_CREATE_SIGNUP: "Signup failed.",
      DOMAIN_NAME_EXIST: "Domain name already exist.",
    },
    SUBSCRIPTION: {
      PLAN_ID_REQUIRED: "Plan Id Required.",
      SUBSCRIPTION_ID_REQUIRED: "Subscription Id Required.",
      PLAN_CREATED: "Plan created successfully.",
      PLAN_UPDATED: "Plan updated successfully.",
      FAILED_TO_CREATE_PLAN: "Failed to create plan.",
      FAILED_TO_UPDATE_PLAN: "Failed to update plan.",
      SUBSCRIPTION_CREATED: "Subscription created successfully.",
      SUBSCRIPTION_UPDATED: "Subscription updated successfully.",
      FAILED_TO_CREATE_SUBSCRIPTION: "Failed to create Subscription.",
      FAILED_TO_UPDATE_SUBSCRIPTION: "Failed to update Subscription.",
    },
    ROLE: {
      ROLE_ID_REQUIRED: "Role Id Required.",
      ROLE_CREATED: "Role created successfully.",
      ROLE_UPDATED: "Role updated successfully.",
      FAILED_TO_CREATE_ROLE: "Failed to create Role.",
      FAILED_TO_UPDATE_ROLE: "Failed to update Role.",
    },
    GENERAL: {
      SOMETHING_WENT_WRONG: "Sorry, something went wrong.",
      VALIDATION_FAILED: "Request data is invalid.",
      USER_NOT_ACCESS_TO_CHANGE_STATUS:
        "You dont have permission to change the status.",
      VALID_LICENSE_NOT_EXIST: "Valid license does not exist.",
      STATUS_UPDATED: "Status updated successfully.",
      UNAUTHORIZED_ACCESS: "Unauthorized access",
      FAILED_TO_GET_DETAILS: "Failed to get details.",
    },
    COURSE: {
      COURSE_CATEGORY_CREATED: "Course category created successfully.",
      COURSE_CATEGORY_EXISTS: "Course category Already Exists.",
      FAILED_TO_CREATE_COURSE_CATEGORY: "Failed to create course category.",
      COURSE_CATEGORY_UPDATED: "Course category updated successfully.",
      COURSE_CATEGORY_LISTED: "Course category listed successfully.",
      FAILED_TO_UPDATE_COURSE_CATEGORY: "Failed to update course category.",
      FAILED_TO_LIST_COURSE_CATEGORY: "Failed to list course category.",
      COURSE_CATEGORY_ID_REQUIRED: "Category Id is required.",
      COURSE_SUB_CATEGORY_CREATED: "Course sub-category created successfully.",
      FAILED_TO_CREATE_COURSE_SUB_CATEGORY:
      "Failed to create course sub-category.",
      COURSE_SUB_CATEGORY_UPDATED: "Course sub-category updated successfully.",
      COURSE_SUB_CATEGORY_EXISTS: "Course sub category Already Exists.",
      FAILED_TO_LIST_SUBCOURSE_CATEGORY: "Failed to list sub course category.",
      COURSE_SUBCATEGORY_LISTED: "Course sub category listed successfully.",
      FAILED_TO_UPDATE_COURSE_SUB_CATEGORY:
        "Failed to update course sub-category.",
      COURSE_SUB_CATEGORY_ID_REQUIRED: "Sub-category Id is required.",
      COURSE_ID_REQUIRED: "Course Id required.",
      COURSE_UPDATED: "Course updated successfully.",
      COURSE_LISTED: "Courses listed successfully.",
      COURSE_FAILED_TO_UPDATE: "Failed to update course.",
      COURSE_NOT_EXIST: "Course not exist.",
      CHAPTER_ADDED: "Chapter added successfully.",
      CHAPTER_ALREADY_ADDED: "Chapter already Exists with this chapterId and chapterOrder.",
      CHAPTER_UPDATED: "Chapter updated successfully.",
      CHAPTER_LISTED: "Chapter listed successfully.",
      CHAPTER_LISTED_FAILED: "Chapter failed list.",
      COURSE_CONTENT_ADDED: "Content added successfully.",
      COURSE_CONTENT_ADDED_FAILED: "Failed to add content.",
      COURSE_CONTENT_ALREADY_EXISTS: "Content already existsm.",
      COURSE_CONTENT_UPDATED: "Content updated successfully.",
      COURSE_CONTENT_UPDATE_FAILED: "Failed to updated content.",
      COURSE_CONTENT_LIST: "Contents list.",
      COURSE_CONTENT_LIST_FAILED: "Failed to list content.",
      LECTURES_REQUIRED: "Lecture array is empty.",
      FAILED_TO_UPDATED_CHAPTER: "Failed to update chapter.",
      FAILED_TO_ADD_CHAPTER: "Failed to add chapter.",
      COURSE_CREATED: "Course created successfully.",
      COURSE_ALREADY_EXISTS: "Hey you have already created this course.",
      COURSE_DETAILS_CREATED: "Course details updated successfully.",
      FAILED_TO_CREATE_COURSE: "Failed to create course.",
      FAILED_TO_CREATE_COURSE_DETAILS: "Failed to create course details.",
      COURSE_QUIZ_SETTINGS_SAVED: "Course quiz settings saved successfully.",
      GET_COURSE_QUIZ_SETTINGS: "Course quiz settings found successfully.",
      COURSE_QUIZ_SETTINGS_NOT_EXIST: "Course quiz settings does not exist.",
      COURSE_QUIZ_QUESTION_ADDED: "Course quiz question added successfully.",
      COURSE_QUIZ_QUESTION_EDITED: "Course quiz question edited successfully.",
      COURSE_QUIZ_QUESTION_DELETED:
        "Course quiz question deleted successfully.",
      COURSE_QUIZ_DATA_DELETED: "Course quiz data deleted successfully.",
      COURSE_QUIZ_QUESTION_STATUS_CHANGED:
        "Course quiz question status changed successfully.",
      GET_COURSE_QUIZ_QUESTIONS: "Course quiz question found successfully.",
      COURSE_QUIZ_QUESTIONS_NOT_EXIST: "Course quiz question does not exist.",
      COURSE_QUIZ_QUESTION_ATTEMPTED:
        "Course quiz question attempted successfully.",
      NO_ACCESS_TO_MODIFY_COURSE_QUIZ_DATA:
        "You dont have permission to modify course quiz data.",
      COURSE_QUIZ_STATUS_CHANGED: "Course quiz status changed successfully.",
    },
    BRANCH: {
      BRANCH_UPDATED: "branch updated successfully.",
      BRANCH_CREATED: "branch created successfully.",
      BRANCH_DETAILS_CREATED: "branch details updated successfully.",
      BRANCH_FAILED_TO_UPDATE: "Failed to update branch.",
      BRANCH_NOT_EXIST: "branch not exist.",
      FAILED_TO_CREATE_BRANCH: "Failed to create branch.",
    },
    USER_TYPE: {
      USER_TYPE_CREATED: "User type created successfully",
      FAILED_TO_CREATE_USER_TYPE: "Failed to create user type",
      USER_TYPE_UPDATED: "User type updated successfully",
      FAILED_TO_UPDATE_USER_TYPE: "Failed to update user type",
      IS_DEFAULT: "default user_type canont be updated",
      USER_TYPE_DELETED: "deleted user type",
      FAILED_TO_DELETE_USER_TYPE: "Failed to delete usertype",
      NON_EXISTING_USER_TYPE: "User type invalid.",
      NO_USER_TYPE: "No user types available.",
    },
    S3: {
      FILE_UPLOADED: "File uploaded successfully.",
      FILE_UPLOAD_FAILED: "Failed to upload file",
      INVALID_CATEGORY: "Invalid file category.",
      INVALID_FILE_EXTENSION: "Invalid file extension.",
      FOLDER_ALREADY_EXIST: "Folder already exist.",
      INVALID_FOLDER_NAME: "Invalid folder name.",
    },
    SETTINGS: {
      UPDATE_SETTINGS: "Settings updated successfully.",
      UPDATE_FAILED: "Failed to update settings.",
    },
    MODULES: {
      MODULE_CREATED: "Module created successfully.",
      MODULE_UPDATED: "Module updated successfully.",
      FAILED_TO_CREATE_MODULE: "Failed to created module.",
      FAILED_TO_UPDATE_MODULE: "Failed to update module.",
      MODULE_SUB_CREATED: "Sub module created successfully.",
      MODULE_SUB_UPDATED: "Sub module updated successfully.",
      FAILED_TO_CREATE_SUB_MODULE: "Failed to created sub module.",
      FAILED_TO_UPDATE_SUB_MODULE: "Failed to update sub module.",
      MODULE_ID_REQUIRED: "Module Id is required.",
      MODULE_PERMISSION_ADDED: "Module permissions added successfully.",
      FAILED_TO_ADD_MODULE_PERMISSIONS: "Failed to create module permissions.",
    },
    REVIEWS: {
      REVIEW_CREATED: "Review created successfully.",
      REVIEW_DELETED: "Review deleted successfully.",
      REVIEW_DELETE_FAILED: "Failed to review deleted successfully.",
      REVIEW_UPDATED: "Review updated successfully.",
      REVIEW_LISTED: "Reviews listed successfully.",
      REVIEW_LISTED_FAILED: "Failed to list Reviews.",
      REVIEW_ALREADY_EXISTS:
        "You have already given the REVIEW, You can update it.",
      FAILED_TO_CREATE_REVIEW: "Failed to create REVIEW.",
      FAILED_TO_UPDATE_REVIEW: "Failed to update REVIEW.",
      NO_REVIEWS: "No Review Found, You can add review!",
    },
    ROLES: {
      ROLE_ALREADY_EXIST: "Role already exist.",
      USER_ROLE_INVALID: "Invalid user role.",
      ROLE_CODE_REQUIRED: "Role code is required.",
      TYPE_INVALID: "Invalid userType.",
    },
    CERTIFICATES: {
      ADDED_CERTIFICATE: "Added certificate successfully.",
      FAILED_TO_ADD_CERTIFICATE: "Failed to add certificate.",
      FETCHED_CERTIFICATE: "Fetched cerificates successfully.",
      UPDATED_CERTIFICATE: "Updated certificate successfully.",
      FAILED_TO_UPDATE: "Failed to update certificate.",
      NOT_FOUND: "Certificate not found.",
    },
  },
  CODES: {
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    VALIDATION_FAILED: 400,
    NOT_FOUND: 404,
    CONFLICT: 409,
    SOMETHING_WENT_WRONG: 412,
    SUCCESS: 200,
    CREATED: 201,
    SUCCESS_WITHOUT_ENTITY: 204,
  },
  ROLES: {
    SYSTEM: "super-admin",
    ADMIN: "admin",
    USER: "user",
  },
};
